schema_version: 1

context:
  name: datafiles
  version: "2.4"
  python_min: 3.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/datafiles-${{ version }}.tar.gz
  sha256: 9a5e87c7bd01481b4efc0f9b53cd2a3277aad60a22dc1a3717df97ad4ead780b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}.0,<4.0.0
    - json-five >=1.1.2,<2.0.0
    - ruamel.yaml >=0.18.10,<0.19.0
    - tomlkit >=0.10.1,<0.11.0
    - parse >=1.12.0,<2.0.0
    - cached_property >=1.5.0,<2.0.0
    - classproperties >=0.2.0,<0.3.0
    - minilog >=2.3.0,<3.0.0

tests:
  - python:
      imports:
        - datafiles
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: File-based ORM for dataclasses.
  license: MIT
  license_file: LICENSE.md
  homepage: https://pypi.org/project/datafiles

extra:
  recipe-maintainers:
    - jacebrowning
    - diegoferigo
